name: imgur_gallery
description: Gallery for imgur

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_platform_widgets: 0.12.0
  cupertino_icons: ^0.1.2
  provider: ^3.0.0
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true