name: pictury
description: Gallery for unsplash

version: 1.0.0+1

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_platform_widgets: 0.12.0
  cupertino_icons: ^0.1.2
  provider: ^3.0.0
  http:
  json_annotation:
  shared_preferences: 0.5.3+4
  streaming_shared_preferences: ^1.0.1
  cached_network_image: 1.1.1
  flutter_staggered_grid_view: 0.3.0
  firebase_remote_config: 0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable: 1.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/lang/en.json
  fonts:
    - family: Sans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
