name: pictury
description: Gallery for unsplash

version: 1.0.0+1

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_platform_widgets: 0.12.0
  provider: 3.1.0
  http:
  shared_preferences: 0.5.3+4
  streaming_shared_preferences: ^1.0.1
  cached_network_image: 1.1.1
  flutter_staggered_grid_view: 0.3.0
  firebase_remote_config: 0.2.0
  bloc: 0.15.0
  flutter_bloc: 0.21.0
  built_value: 6.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  built_value_generator: 6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/lang/en.json
  fonts:
    - family: Sans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
