name: wallpaper_changer
description: Flutter plugin to set wallpaper
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.11.3+17

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.regin.wallpaper_changer
    pluginClass: WallpaperChangerPlugin